name: vsss

on:
  pull_request:
    paths-ignore: 
      - README.md
      - SECURITY.md
      - LICENSE-APACHE
      - LICENSE-MIT
      - .pants-ignore
      - rustfmt.toml
  push:
    branches: main
    paths-ignore:
      - README.md
      - SECURITY.md
      - LICENSE-APACHE
      - LICENSE-MIT
      - .pants-ignore
      - rustfmt.toml

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  RUST_LOG_STYLE: always
  RUSTFLAGS: "-Dwarnings"
  RUSTDOCFLAGS: "-Dwarnings"

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - run: cargo build --all-features

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - run: cargo test --all-features --release

  careful:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with: 
          toolchain: nightly
      - uses: cargo-bins/cargo-binstall@main
      - run: cargo binstall --no-confirm cargo-careful
      - run: cargo careful test tests --release
        
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy
      - run: cargo clippy --all --all-features -- -D warnings

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt
      - run: cargo fmt -- --check

  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - run: cargo doc --all-features

  deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
      - uses: cargo-bins/cargo-binstall@main
      - run: cargo binstall --no-confirm cargo-udeps
      - run: cargo udeps --all-targets --all-features

  outdated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
      - uses: cargo-bins/cargo-binstall@main
      - run: cargo binstall --no-confirm cargo-outdated
      - run: cargo outdated --root-deps-only --exit-code 1 --exclude rand_core --exclude crypto-bigint --ignore rand_core --ignore crypto-bigint

  pants:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
      - uses: cargo-bins/cargo-binstall@main
      - run: cargo binstall --no-confirm cargo-pants
      - run: cargo pants --loud --dev
